src/Entity/Session.php
<?php

namespace App\Entity;

use DatePeriod;
use DateInterval;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\SessionRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $placeDisponibles = null;

    #[ORM\Column]
    private ?\DateTime $dateDebut = null;

    #[ORM\Column]
    private ?\DateTime $dateFin = null;

    #[ORM\Column]
    private ?int $placeRestantes = null;

    #[ORM\Column]
    private ?int $placeReservees = null;

    /**
     * @var Collection<int, Stagiaire>
     */
    #[ORM\ManyToMany(targetEntity: Stagiaire::class, mappedBy: 'sessions')]
    private Collection $stagiaires;

    /**
     * @var Collection<int, Programme>
     */
    #[ORM\OneToMany(targetEntity: Programme::class, mappedBy: 'session', orphanRemoval: true)]
    private Collection $programmes;

    public function __construct()
    {
        $this->stagiaires = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPlaceDisponibles(): ?int
    {
        return $this->placeDisponibles;
    }

    public function setPlaceDisponibles(int $placeDisponibles): static
    {
        $this->placeDisponibles = $placeDisponibles;

        return $this;
    }

    public function getDateDebut(): ?\DateTime
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTime $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTime
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTime $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getPlaceRestantes(): ?int
    {
        return $this->placeRestantes;
    }

    public function setPlaceRestantes(int $placeRestantes): static
    {
        $this->placeRestantes = $placeRestantes;

        return $this;
    }

    public function getPlaceReservees(): ?int
    {
        return $this->placeReservees;
    }

    public function setPlaceReservees(int $placeReservees): static
    {
        $this->placeReservees = $placeReservees;

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): static
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->add($stagiaire);
            $stagiaire->addSession($this);
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): static
    {
        if ($this->stagiaires->removeElement($stagiaire)) {
            $stagiaire->removeSession($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

 
    // Calcule des places restantes automatiquement
    public function getNbPlacesRestantes(): ?int
    {
        if ($this->placeDisponibles === null || $this->placeReservees === null) {
            return null;
        }

        return $this->placeDisponibles - $this->placeReservees;
    }


    //  Méthode pour savoir quand la session est complète
    public function estComplet(): bool
    {
        return $this->placeReservees >= $this->placeDisponibles;
    }


       // Méthode savoir la durée session : 
    public function DureeSession(): int
    {
        $debut = $this->getDateDebut();
        $fin = $this->getDateFin();

          if (!$debut || !$fin || $debut >= $fin) {
            return 0; 
            }

        // car dateperiod exclut la date de la fin
        $fin->modify('+1 day'); // ?

        $interval = $fin ->diff($debut);

        // jours total
        $jours = $interval -> days ;

        // create an iterateable period of date (P1D equates to 1 day)
        $periode = new DatePeriod($debut, new DateInterval('P1D'), $fin);

        $ferie = array('2025-01-01', '2025-04-21', '2025-05-01', '2025-05-08', '2025-05-29', 
                    '2025-06-09', '2025-07-14', '2025-08-15', '2025-11-01', '2025-11-11', '2025-12-25', '2025-12-26', '2025-04-18'); 
        // Les deux derniers c'est l'Alsace Moselle, + deux jours fériés

        foreach($periode as $dt) {
            $curr = $dt->format('D');
        
            // substract if Saturday or Sunday
        if ($curr == 'Sat' || $curr == 'Sun') {
            $jours--; // -- c'est pour soustraire 
        }

        elseif (in_array($dt->format('Y-m-d'), $ferie)) {
        $jours--;
        }
        
        }

        return $jours;
    }

}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Stagiaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Nom de la session'
            ])
            ->add('placeDisponibles', IntegerType::class, [
                'label' => 'Places disponibles'
            ])
            ->add('dateDebut', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date de début'
            ])
            ->add('dateFin', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date de fin'
            ])
            ->add('placeRestantes', IntegerType::class, [
                'label' => 'Places restantes'
            ])
            ->add('placeReservees', IntegerType::class, [
                'label' => 'Places réservées'
            ])
            ->add('stagiaires', EntityType::class, [
                'class' => Stagiaire::class,
                'choice_label' => function($stagiaire) {
                    return $stagiaire->getNom() . ' ' . $stagiaire->getPrenom();
                },
                'label' => 'Stagiaires inscrits',
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('Valider', SubmitType::class)
        ;
    }

    
    
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Form\SessionType;
use Doctrine\ORM\EntityManager;
use App\Repository\SessionRepository;
use App\Repository\StagiaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


final class SessionController extends AbstractController
{
    /* LISTE  */
        #[Route('/session', name: 'app_session')]
        public function index(SessionRepository $sessionRepository): Response
        {   
            $sessionsPassees = $sessionRepository->findPastSessions();
            $sessionsEnCours = $sessionRepository->findCurrentSessions();
            $sessionsAVenir = $sessionRepository->findUpcomingSessions();
            return $this->render('session/index.html.twig', [
                'sessionsPassees' => $sessionsPassees,
                'sessionsEnCours' => $sessionsEnCours,
                'sessionsAVenir' => $sessionsAVenir,         
            ]);
        }

    /* FORMULAIRE + EDIT */
        // ROUTES : Cette méthode sera appelée lorsqu’un utilisateur accède à /session/new ou /session/{id}/edit
        #[Route('/session/new', name: 'new_session')] // Création d'un nouvelle session 
        #[Route('/session/{id}/edit', name: 'edit_session')] // Modification d'une nouvelle sessions
        public function new(Request $request, EntityManagerInterface $entityManager, Session $session = null): Response
        {
            // Si aucun objet Session n’est fourni (cas du /new), on en crée un vide
            if (!$session) {
                $session = new Session(); // création d'un objet vide à remplir
            }

            // On génère le formulaire à partir de la classe SessionType
            // On le lie directement à l’objet $session (création ou modification)
            $form = $this->createForm(SessionType::class, $session); // Génère un formulaire basé sur une classe

            // On relie le formulaire aux données envoyées dans la requête HTTP
            // Cela permet de détecter s’il a été soumis et de remplir automatiquement l’objet
            $form->handleRequest($request); // Lie les données reçues à l’objet

            // Vérification : si le formulaire a été soumis ET que tous les champs sont valides
            if ($form->isSubmitted() && $form->isValid()) {

                // On récupère les données du formulaire (remplissent automatiquement $session)
                $session = $form->getData();

                if ($session->estComplet()) {
                    $this->addFlash("error", "Impossible d'ajouter des stagiaires : la session est complète.");
                    return $this->redirectToRoute('app_session');
                }

                // On prépare l’objet pour l’insérer (ou mettre à jour) en base de données
                $entityManager->persist($session); // Prepare PDO

                // On exécute l’insertion ou mise à jour dans la base de données
                $entityManager->flush(); // Execute PDO

                // Une fois terminé, on redirige vers la liste des sessions
                return $this->redirectToRoute('app_session');
            }

            // Si le formulaire n’a pas été soumis ou est invalide, on réaffiche la page avec le formulaire
            return $this->render('session/new.html.twig', [
                'formAddSession' => $form,
                'edit' => $session->getId() // Permet d’afficher dynamiquement “Ajouter” ou “Modifier”
            ]);
        }

    /* SUPPRESSION  */

        // ROUTE :
        #[Route('/session/{id}/delete', name: 'delete_session')]
        public function delete(Session $session, EntityManagerInterface $entityManager): Response
        {
            // On supprime la session de la base de données
            $entityManager->remove($session); // Prépare la suppression
            $entityManager->flush(); // Exécute la suppression

            // Redirection vers la liste des sessions
            return $this->redirectToRoute('app_session');
        }


    /* DETAIL  */
        #[Route('/session/{id}', name: 'show_session')]
        public function show(Session $session = null, SessionRepository $sr): Response
        {
            $nonInscrits = $sr->findNonInscrits($session->getId());
            $nonProgrammes = $sr->findNonProgrammes($session->getId());

            return $this->render('session/show.html.twig', [
            'session' => $session,
            'nonInscrits'=> $nonInscrits,
            'nonProgrammes' => $nonProgrammes,
            ]);
        }
  

    /* INSCRIPTION d’un stagiaire à une session */
        #[Route('/session/{idSession}/{idStagiaire}/add', name: 'add_stagiaire_session')]
        public function addStagiaireToSession( EntityManagerInterface $entityManager, $idSession, $idStagiaire,
        SessionRepository $SessionRepository, StagiaireRepository $StagiaireRepository ): Response {
            // 1) On récupère la session et le stagiaire en base
            $session   = $SessionRepository->find($idSession);
            $stagiaire = $StagiaireRepository->find($idStagiaire);

            if ($session && $stagiaire) {
                // 2) On vérifie si la session est complète
                if ($session->estComplet()) {
                    $this->addFlash('error', "Impossible d'ajouter ce stagiaire : la session est complète.");
                } else {
                    // 3) On rattache le stagiaire à la session
                    $session->addStagiaire($stagiaire);

                    // 4) On incrémente le nombre de places réservées
                    $session->setPlaceReservees(
                        $session->getPlaceReservees() + 1
                    );

                    // 5) On recalcule le nombre de places restantes
                    $session->setPlaceRestantes(
                        $session->getPlaceDisponibles() - $session->getPlaceReservees()
                    );

                    // 6) On enregistre les modifications en base
                    $entityManager->persist($session);
                    $entityManager->flush();

                    $this->addFlash('success', "Le stagiaire a bien été inscrit à la session.");
                }

                // 7) Redirection vers le détail de la session
                return $this->redirectToRoute('show_session', ['id' => $idSession]);
            }

            // session ou stagiaire introuvable : retour à la liste
            return $this->redirectToRoute('app_session');
        }


    /* DÉSINSCRIPTION d’un stagiaire à une session */
        #[Route('/session/{idSession}/{idStagiaire}/remove', name: 'remove_stagiaire_session')]
        public function removeStagiaireFromSession( EntityManagerInterface $entityManager, $idSession, $idStagiaire,
        SessionRepository $SessionRepository, StagiaireRepository $StagiaireRepository ): Response {
           
            // 1) On récupère la session et le stagiaire en base
            $session   = $SessionRepository->find($idSession);
            $stagiaire = $StagiaireRepository->find($idStagiaire);

            if ($session && $stagiaire) {
                // 2) On détache le stagiaire de la session
                $session->removeStagiaire($stagiaire);

                // 3) On décrémente le nombre de places réservées
                $session->setPlaceReservees(
                    $session->getPlaceReservees() - 1
                );

                // 4) On recalcule le nombre de places restantes
                $session->setPlaceRestantes(
                    $session->getPlaceDisponibles() - $session->getPlaceReservees()
                );

                // 5) On enregistre les modifications en base
                $entityManager->persist($session);
                $entityManager->flush();

                $this->addFlash('success', "Le stagiaire a bien été désinscrit de la session.");
            }

            // Redirection vers le détail de la session
            return $this->redirectToRoute('show_session', ['id' => $idSession]);
        }



}

templates/session/index.html.twig
{% extends 'base.html.twig' %} 

{% block title %} Liste des Sessions {% endblock %}

{% block body %}

    <div class="bloc-titre-page">
        <h1>📚 Gestion des Sessions</h1>
        <h2> Liste • Ajout • Modification • Suppression des sessions de formation</h2>
    </div>

    <!-- Sessions passées -->
    <div class="tableau-k">
       
        <p class="titre-tableau">📋 Sessions Passées ( {{ sessionsPassees|length }} )</p>
       
        <table>
            <thead>
                <tr>
                    <th>Intitulé</th>
                    <th>Date de début</th>
                    <th>Date de fin</th>
                    <th>Détails</th>
                </tr>
            </thead>
           
            <tbody>
                {% for session in sessionsPassees %}
                    <tr>
                        <td>{{ session.nom }}</td>
                        <td>{{ session.dateDebut|date('d/m/Y') }}</td>
                        <td>{{ session.dateFin|date('d/m/Y') }}</td>
                        <td><a href="{{ path('show_session', {id: session.id}) }}">👁️</a>
                            <a href="{{ path('edit_session', {'id': session.id}) }}">✏️</a>
                            <a href="{{ path('delete_session', {'id': session.id}) }}">🗑️</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!--  Sessions en cours -->
    <div class="tableau-k">
       
        <p class="titre-tableau">📘 Sessions en cours ({{ sessionsEnCours|length }})</p>
       
        <table>

            <thead>
                <tr>
                    <th>Intitulé</th>
                    <th>Date de début</th>
                    <th>Date de fin</th>
                    <th>Détails</th>
                </tr>
            </thead>
          
            <tbody>
                {% for session in sessionsEnCours %}
                    <tr>
                        <td>{{ session.nom }}</td>
                        <td>{{ session.dateDebut|date('d/m/Y') }}</td>
                        <td>{{ session.dateFin|date('d/m/Y') }}</td>
                        <td><a href="{{ path('show_session', {id: session.id}) }}">👁️</a>
                            <a href="{{ path('edit_session', {'id': session.id}) }}">✏️</a>
                            <a href="{{ path('delete_session', {'id': session.id}) }}">🗑️</a>                   
                        </td>
                    </tr>
                {% endfor %}

            </tbody>
        
        </table>
    </div>

    <!--  Sessions à venir -->
    <div class="tableau-k">

        <p class="titre-tableau">📗 Sessions à venir ({{ sessionsAVenir|length }})</p>

        <table>
            <thead>
                <tr>
                    <th>Intitulé</th>
                    <th>Date de début</th>
                    <th>Date de fin</th>
                    <th>Détails</th>
                </tr>
            </thead>

            <tbody>
                {% for session in sessionsAVenir %}
                    <tr>
                        <td>{{ session.nom }}</td>
                        <td>{{ session.dateDebut|date('d/m/Y') }}</td>
                        <td>{{ session.dateFin|date('d/m/Y') }}</td>
                        <td><a href="{{ path('show_session', {id: session.id}) }}">👁️</a>
                            <a href="{{ path('edit_session', {'id': session.id}) }} ">✏️</a>
                            <a href="{{ path('delete_session', {'id': session.id}) }}">🗑️</a>                       
                        </td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>
        
    </div>

{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une session{% endblock %}

{% block body %}

    <div class="bloc-titre-page">
        {% if edit %}
            <h1>Modifier une session</h1>
        {% else %}
            <h1>Ajouter une session</h1>
        {% endif %}
    </div>

    <div>
        {{ form(formAddSession) }}
    </div>

{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de la session{% endblock %}

{% block body %}

    <div class="bloc-titre-page"> 
            <h1>Détail de la Session</h1> {# TROUVER TWIG POUR CALCULE LA DIFF ENTRE DATE #}
        </div>

    <p><strong>Nom :</strong> {{ session.nom }}</p>

    <p><strong>Date de début :</strong> {{ session.dateDebut|date('d/m/Y') }}</p>
    <p><strong>Date de fin :</strong> {{ session.dateFin|date('d/m/Y') }}</p>

    <p><strong>Durée de la session :</strong> {{ session.DureeSession() }} (jours ouvrés) </p>

    <p><strong>Places disponibles :</strong> {{ session.placeDisponibles }}</p>

    <p><strong>Places réservées :</strong> {{ session.placeReservees }}</p>
    <p><strong>Places restantes :</strong> {{ session.nbPlacesRestantes  }}</p>

        {% if session.estComplet %}
            <p style="color: red"> Cette session est complète. Aucune inscription possible.</p>
        {% else %}
            <p> Des places sont encore disponibles.</p>
        {% endif %}

    <h2>Stagiaires inscrits ({{ session.stagiaires|length }})</h2>

    {% if session.stagiaires|length > 0 %}
        <ul>
            {% for stagiaire in session.stagiaires %}
                <li>{{ stagiaire.nom }} {{ stagiaire.prenom }}
                <a href="{{ path('remove_stagiaire_session', {idSession: session.id, idStagiaire: stagiaire.id}) }}"> Retirer</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Aucun stagiaire inscrit.</p>
    {% endif %}

        <h2>Liste des stagiaires non inscrits</h2>

        <ul>
            {% for stagiaire in nonInscrits %}
                <li><a href="{{ path('add_stagiaire_session', { idSession: session.id, idStagiaire: stagiaire.id }) }}">Ajouter à la liste des inscrits</a>  {{ stagiaire.nom }} {{ stagiaire.prenom }}</li> 
            {% else %}
                <li>Aucun stagiaire à inscrire.</li>
            {% endfor %}
        </ul>

    <p>
        <a style="color: white" href="{{ path('app_session') }}">← Retour à la liste des sessions</a>
    </p>

    <h2>Programme de la session ({{ session.programmes|length }})</h2>

    <div>
        {% if session.programmes|length > 0 %}

            {% set totalJours = 0 %}

            <table>
                <thead>
                    <tr>
                        <th>Nom du Module</th>
                        <th>Nombre de jours</th>
                    </tr>
                </thead>
                <tbody>
                    {% for programme in session.programmes %} {# Mieux lire les S #}
                        <tr>
                            <td>{{ programme.module.nom }}</td>
                            <td>{{ programme.nbJours }}</td>
                        </tr>
                    
                        {% set totalJours = totalJours + programme.nbJours %}
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th>Total des jours</th>
                        <th>{{ totalJours }}</th>
                    </tr>
                </tfoot>
            </table>

        {% else %}

            <p>Aucun module prévu pour cette session.</p>
            
        {% endif %}
    </div>

    <div>
        <h2>Module hors session </h2>

        <ul>
            {% for module in nonProgrammes %}
                <li> {{ module.nom}} </li>
                {% else %}
                <li> Aucun module à rajouter </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}